Got the new linking working.
git-svn-id: svn://disks/svn/dm-3.2/trunk@310 71cd2e2a-5bfc-0310-b9d0-8a5a8567c16d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -31817,319 +31817,7 @@ fi
 
 
 
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src from codegen/dsp1f.h.built to disp1f.h" >&5
-echo $ECHO_N "checking symlink in src from codegen/dsp1f.h.built to disp1f.h... $ECHO_C" >&6
-  if (cd "src" \
-      && (if test -e "disp1f.h" || test -L "disp1f.h" ; then rm -f "disp1f.h" ; else : ; fi) \
-      && ${LN_S} "codegen/dsp1f.h.built" "disp1f.h") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src from codegen/dmnuminc.h.built to dmnuminc.h" >&5
-echo $ECHO_N "checking symlink in src from codegen/dmnuminc.h.built to dmnuminc.h... $ECHO_C" >&6
-  if (cd "src" \
-      && (if test -e "dmnuminc.h" || test -L "dmnuminc.h" ; then rm -f "dmnuminc.h" ; else : ; fi) \
-      && ${LN_S} "codegen/dmnuminc.h.built" "dmnuminc.h") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-
-
-
-
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../dm.h to dm.h" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../dm.h to dm.h... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "dm.h" || test -L "dm.h" ; then rm -f "dm.h" ; else : ; fi) \
-      && ${LN_S} "../dm.h" "dm.h") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../dmglobals.c to dmglobals.c" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../dmglobals.c to dmglobals.c... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "dmglobals.c" || test -L "dmglobals.c" ; then rm -f "dmglobals.c" ; else : ; fi) \
-      && ${LN_S} "../dmglobals.c" "dmglobals.c") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../dsp1.c to dsp1.c" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../dsp1.c to dsp1.c... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "dsp1.c" || test -L "dsp1.c" ; then rm -f "dsp1.c" ; else : ; fi) \
-      && ${LN_S} "../dsp1.c" "dsp1.c") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../dsp2.c to dsp2.c" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../dsp2.c to dsp2.c... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "dsp2.c" || test -L "dsp2.c" ; then rm -f "dsp2.c" ; else : ; fi) \
-      && ${LN_S} "../dsp2.c" "dsp2.c") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../dm1.c to dm1.c" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../dm1.c to dm1.c... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "dm1.c" || test -L "dm1.c" ; then rm -f "dm1.c" ; else : ; fi) \
-      && ${LN_S} "../dm1.c" "dm1.c") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../dm2.c to dm2.c" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../dm2.c to dm2.c... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "dm2.c" || test -L "dm2.c" ; then rm -f "dm2.c" ; else : ; fi) \
-      && ${LN_S} "../dm2.c" "dm2.c") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../dm3.c to dm3.c" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../dm3.c to dm3.c... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "dm3.c" || test -L "dm3.c" ; then rm -f "dm3.c" ; else : ; fi) \
-      && ${LN_S} "../dm3.c" "dm3.c") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../dm4.c to dm4.c" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../dm4.c to dm4.c... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "dm4.c" || test -L "dm4.c" ; then rm -f "dm4.c" ; else : ; fi) \
-      && ${LN_S} "../dm4.c" "dm4.c") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../dm5.c to dm5.c" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../dm5.c to dm5.c... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "dm5.c" || test -L "dm5.c" ; then rm -f "dm5.c" ; else : ; fi) \
-      && ${LN_S} "../dm5.c" "dm5.c") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../dm6.c to dm6.c" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../dm6.c to dm6.c... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "dm6.c" || test -L "dm6.c" ; then rm -f "dm6.c" ; else : ; fi) \
-      && ${LN_S} "../dm6.c" "dm6.c") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../dm7.c to dm7.c" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../dm7.c to dm7.c... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "dm7.c" || test -L "dm7.c" ; then rm -f "dm7.c" ; else : ; fi) \
-      && ${LN_S} "../dm7.c" "dm7.c") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../dm8.c to dm8.c" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../dm8.c to dm8.c... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "dm8.c" || test -L "dm8.c" ; then rm -f "dm8.c" ; else : ; fi) \
-      && ${LN_S} "../dm8.c" "dm8.c") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../dmnum.c to dmnum.c" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../dmnum.c to dmnum.c... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "dmnum.c" || test -L "dmnum.c" ; then rm -f "dmnum.c" ; else : ; fi) \
-      && ${LN_S} "../dmnum.c" "dmnum.c") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../error-local.h to error-local.h" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../error-local.h to error-local.h... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "error-local.h" || test -L "error-local.h" ; then rm -f "error-local.h" ; else : ; fi) \
-      && ${LN_S} "../error-local.h" "error-local.h") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../paths.h.in to paths.h.in" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../paths.h.in to paths.h.in... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "paths.h.in" || test -L "paths.h.in" ; then rm -f "paths.h.in" ; else : ; fi) \
-      && ${LN_S} "../paths.h.in" "paths.h.in") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../threads.c to threads.c" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../threads.c to threads.c... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "threads.c" || test -L "threads.c" ; then rm -f "threads.c" ; else : ; fi) \
-      && ${LN_S} "../threads.c" "threads.c") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-  echo "$as_me:$LINENO: checking symlink in src/codegen from ../threads.h to threads.h" >&5
-echo $ECHO_N "checking symlink in src/codegen from ../threads.h to threads.h... $ECHO_C" >&6
-  if (cd "src/codegen" \
-      && (if test -e "threads.h" || test -L "threads.h" ; then rm -f "threads.h" ; else : ; fi) \
-      && ${LN_S} "../threads.h" "threads.h") ; then
-    echo "$as_me:$LINENO: result: linked" >&5
-echo "${ECHO_T}linked" >&6
-  else
-    { { echo "$as_me:$LINENO: error: Unable to link" >&5
-echo "$as_me: error: Unable to link" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
+                                                                                                                                                                                              ac_config_links="$ac_config_links src/dsp1f.h:src/codegen/dsp1f.h.built src/dmnuminc.h:src/codegen/dmnuminc.h.built src/codegen/dm.h:src/dm.h src/codegen/dmglobals.c:src/dmglobals.c src/codegen/dsp1.c:src/dsp1.c src/codegen/dsp2.c:src/dsp2.c src/codegen/dm1.c:src/dm1.c src/codegen/dm2.c:src/dm2.c src/codegen/dm3.c:src/dm3.c src/codegen/dm4.c:src/dm4.c src/codegen/dm5.c:src/dm5.c src/codegen/dm6.c:src/dm6.c src/codegen/dm7.c:src/dm7.c src/codegen/dm8.c:src/dm8.c src/codegen/dmnum.c:src/dmnum.c src/codegen/error-local.h:src/error-local.h src/codegen/paths.h.in:src/paths.h.in src/codegen/threads.c:src/threads.c src/codegen/threads.h:src/threads.h"
 
 
                                                                                                                                   ac_config_files="$ac_config_files Makefile src/Makefile src/codegen/Makefile src/codegen/startup_dgen.d src/codegen/dmnuminc.d plugins/Makefile ps/Makefile sh/Makefile emacs/Makefile emacs/d-mode.el dcode/Makefile dcode/startup_dvt.d dcode/startup_dnode.d"
@@ -32664,6 +32352,9 @@ $config_files
 Configuration headers:
 $config_headers
 
+Configuration links:
+$config_links
+
 Configuration commands:
 $config_commands
 
@@ -32795,6 +32486,25 @@ do
   "dcode/Makefile" ) CONFIG_FILES="$CONFIG_FILES dcode/Makefile" ;;
   "dcode/startup_dvt.d" ) CONFIG_FILES="$CONFIG_FILES dcode/startup_dvt.d" ;;
   "dcode/startup_dnode.d" ) CONFIG_FILES="$CONFIG_FILES dcode/startup_dnode.d" ;;
+  "src/dsp1f.h" ) CONFIG_LINKS="$CONFIG_LINKS src/dsp1f.h:src/codegen/dsp1f.h.built" ;;
+  "src/dmnuminc.h" ) CONFIG_LINKS="$CONFIG_LINKS src/dmnuminc.h:src/codegen/dmnuminc.h.built" ;;
+  "src/codegen/dm.h" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/dm.h:src/dm.h" ;;
+  "src/codegen/dmglobals.c" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/dmglobals.c:src/dmglobals.c" ;;
+  "src/codegen/dsp1.c" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/dsp1.c:src/dsp1.c" ;;
+  "src/codegen/dsp2.c" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/dsp2.c:src/dsp2.c" ;;
+  "src/codegen/dm1.c" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/dm1.c:src/dm1.c" ;;
+  "src/codegen/dm2.c" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/dm2.c:src/dm2.c" ;;
+  "src/codegen/dm3.c" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/dm3.c:src/dm3.c" ;;
+  "src/codegen/dm4.c" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/dm4.c:src/dm4.c" ;;
+  "src/codegen/dm5.c" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/dm5.c:src/dm5.c" ;;
+  "src/codegen/dm6.c" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/dm6.c:src/dm6.c" ;;
+  "src/codegen/dm7.c" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/dm7.c:src/dm7.c" ;;
+  "src/codegen/dm8.c" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/dm8.c:src/dm8.c" ;;
+  "src/codegen/dmnum.c" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/dmnum.c:src/dmnum.c" ;;
+  "src/codegen/error-local.h" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/error-local.h:src/error-local.h" ;;
+  "src/codegen/paths.h.in" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/paths.h.in:src/paths.h.in" ;;
+  "src/codegen/threads.c" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/threads.c:src/threads.c" ;;
+  "src/codegen/threads.h" ) CONFIG_LINKS="$CONFIG_LINKS src/codegen/threads.h:src/threads.h" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -32810,6 +32520,7 @@ done
 if $ac_need_defaults; then
   test "${CONFIG_FILES+set}" = set || CONFIG_FILES=$config_files
   test "${CONFIG_HEADERS+set}" = set || CONFIG_HEADERS=$config_headers
+  test "${CONFIG_LINKS+set}" = set || CONFIG_LINKS=$config_links
   test "${CONFIG_COMMANDS+set}" = set || CONFIG_COMMANDS=$config_commands
 fi
 
@@ -33515,6 +33226,144 @@ _ACEOF
 cat >>$CONFIG_STATUS <<\_ACEOF
 
 #
+# CONFIG_LINKS section.
+#
+
+for ac_file in : $CONFIG_LINKS; do test "x$ac_file" = x: && continue
+  ac_dest=`echo "$ac_file" | sed 's,:.*,,'`
+  ac_source=`echo "$ac_file" | sed 's,[^:]*:,,'`
+
+  { echo "$as_me:$LINENO: linking $srcdir/$ac_source to $ac_dest" >&5
+echo "$as_me: linking $srcdir/$ac_source to $ac_dest" >&6;}
+
+  if test ! -r $srcdir/$ac_source; then
+    { { echo "$as_me:$LINENO: error: $srcdir/$ac_source: file not found" >&5
+echo "$as_me: error: $srcdir/$ac_source: file not found" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  rm -f $ac_dest
+
+  # Make relative symlinks.
+  ac_dest_dir=`(dirname "$ac_dest") 2>/dev/null ||
+$as_expr X"$ac_dest" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 X"$ac_dest" : 'X\(//\)[^/]' \| \
+	 X"$ac_dest" : 'X\(//\)$' \| \
+	 X"$ac_dest" : 'X\(/\)' \| \
+	 .     : '\(.\)' 2>/dev/null ||
+echo X"$ac_dest" |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{ s//\1/; q; }
+  	  /^X\(\/\/\)[^/].*/{ s//\1/; q; }
+  	  /^X\(\/\/\)$/{ s//\1/; q; }
+  	  /^X\(\/\).*/{ s//\1/; q; }
+  	  s/.*/./; q'`
+  { if $as_mkdir_p; then
+    mkdir -p "$ac_dest_dir"
+  else
+    as_dir="$ac_dest_dir"
+    as_dirs=
+    while test ! -d "$as_dir"; do
+      as_dirs="$as_dir $as_dirs"
+      as_dir=`(dirname "$as_dir") 2>/dev/null ||
+$as_expr X"$as_dir" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 X"$as_dir" : 'X\(//\)[^/]' \| \
+	 X"$as_dir" : 'X\(//\)$' \| \
+	 X"$as_dir" : 'X\(/\)' \| \
+	 .     : '\(.\)' 2>/dev/null ||
+echo X"$as_dir" |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{ s//\1/; q; }
+  	  /^X\(\/\/\)[^/].*/{ s//\1/; q; }
+  	  /^X\(\/\/\)$/{ s//\1/; q; }
+  	  /^X\(\/\).*/{ s//\1/; q; }
+  	  s/.*/./; q'`
+    done
+    test ! -n "$as_dirs" || mkdir $as_dirs
+  fi || { { echo "$as_me:$LINENO: error: cannot create directory \"$ac_dest_dir\"" >&5
+echo "$as_me: error: cannot create directory \"$ac_dest_dir\"" >&2;}
+   { (exit 1); exit 1; }; }; }
+
+  ac_builddir=.
+
+if test "$ac_dest_dir" != .; then
+  ac_dir_suffix=/`echo "$ac_dest_dir" | sed 's,^\.[\\/],,'`
+  # A "../" for each directory in $ac_dir_suffix.
+  ac_top_builddir=`echo "$ac_dir_suffix" | sed 's,/[^\\/]*,../,g'`
+else
+  ac_dir_suffix= ac_top_builddir=
+fi
+
+case $srcdir in
+  .)  # No --srcdir option.  We are building in place.
+    ac_srcdir=.
+    if test -z "$ac_top_builddir"; then
+       ac_top_srcdir=.
+    else
+       ac_top_srcdir=`echo $ac_top_builddir | sed 's,/$,,'`
+    fi ;;
+  [\\/]* | ?:[\\/]* )  # Absolute path.
+    ac_srcdir=$srcdir$ac_dir_suffix;
+    ac_top_srcdir=$srcdir ;;
+  *) # Relative path.
+    ac_srcdir=$ac_top_builddir$srcdir$ac_dir_suffix
+    ac_top_srcdir=$ac_top_builddir$srcdir ;;
+esac
+
+# Do not use `cd foo && pwd` to compute absolute paths, because
+# the directories may not exist.
+case `pwd` in
+.) ac_abs_builddir="$ac_dest_dir";;
+*)
+  case "$ac_dest_dir" in
+  .) ac_abs_builddir=`pwd`;;
+  [\\/]* | ?:[\\/]* ) ac_abs_builddir="$ac_dest_dir";;
+  *) ac_abs_builddir=`pwd`/"$ac_dest_dir";;
+  esac;;
+esac
+case $ac_abs_builddir in
+.) ac_abs_top_builddir=${ac_top_builddir}.;;
+*)
+  case ${ac_top_builddir}. in
+  .) ac_abs_top_builddir=$ac_abs_builddir;;
+  [\\/]* | ?:[\\/]* ) ac_abs_top_builddir=${ac_top_builddir}.;;
+  *) ac_abs_top_builddir=$ac_abs_builddir/${ac_top_builddir}.;;
+  esac;;
+esac
+case $ac_abs_builddir in
+.) ac_abs_srcdir=$ac_srcdir;;
+*)
+  case $ac_srcdir in
+  .) ac_abs_srcdir=$ac_abs_builddir;;
+  [\\/]* | ?:[\\/]* ) ac_abs_srcdir=$ac_srcdir;;
+  *) ac_abs_srcdir=$ac_abs_builddir/$ac_srcdir;;
+  esac;;
+esac
+case $ac_abs_builddir in
+.) ac_abs_top_srcdir=$ac_top_srcdir;;
+*)
+  case $ac_top_srcdir in
+  .) ac_abs_top_srcdir=$ac_abs_builddir;;
+  [\\/]* | ?:[\\/]* ) ac_abs_top_srcdir=$ac_top_srcdir;;
+  *) ac_abs_top_srcdir=$ac_abs_builddir/$ac_top_srcdir;;
+  esac;;
+esac
+
+
+  case $srcdir in
+  [\\/$]* | ?:[\\/]* ) ac_rel_source=$srcdir/$ac_source ;;
+      *) ac_rel_source=$ac_top_builddir$srcdir/$ac_source ;;
+  esac
+
+  # Try a symlink, then a hard link, then a copy.
+  ln -s $ac_rel_source $ac_dest 2>/dev/null ||
+    ln $srcdir/$ac_source $ac_dest 2>/dev/null ||
+    cp -p $srcdir/$ac_source $ac_dest ||
+    { { echo "$as_me:$LINENO: error: cannot link or copy $srcdir/$ac_source to $ac_dest" >&5
+echo "$as_me: error: cannot link or copy $srcdir/$ac_source to $ac_dest" >&2;}
+   { (exit 1); exit 1; }; }
+done
+_ACEOF
+cat >>$CONFIG_STATUS <<\_ACEOF
+
+#
 # CONFIG_COMMANDS section.
 #
 for ac_file in : $CONFIG_COMMANDS; do test "x$ac_file" = x: && continue
@@ -33920,4 +33769,5 @@ echo "$as_me: error: $ac_sub_configure failed for $ac_dir" >&2;}
     cd $ac_popdir
   done
 fi
+
 
